#!/usr/bin/env bash

# Download fzf
which -a fzf > /dev/null || (
  git clone --depth 2 https://github.com/junegunn/fzf.git $HOME/.fzf && $HOME/.fzf/install --no-update-rc --key-bindings --completion
)

# Install vim-plug then install plugins
if [ ! -e $HOME/.config/nvim/autoload/plug.vim ]; then
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
# vim +'PlugInstall --sync' +qa
